= Introducción a la Programación: Trabajo Práctico 1
Pablo Pagano<cfk@gmail.com>; Jose_Luis Villacorta <nestor@gmail.com>;Alcaraz Sofia <sofiialcaraz16@gmail.com>
v1, {docdate}. Docentes Hernan Rondelli ; Veronica Moyano (COM-01)
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción
El Concejo Org´anico Normativo y ´Etico para la Juventud Organizada (CONEJO),
 en el marco de su campan˜a de seguridad vial, nos solicit´o el desarrollo de 
 un video juego para ayudar a que nin˜os y nin˜as tomen conciencia acerca de la 
 seguridad vial y del respeto a las normas de tr´ansito. Para ello, nos
 encargaron un video juego similar al cl´asico Frogger, pero con algunas
 diferencias que mencionamos a continuaci´on.

El conejo Boss Rabbit que vive en la luna, baj´o al planeta tierra, por
 este motivo no sabe cu´ales son las normas de tr´ansito, y por ende, no 
 sabe cruzar la calle.
El objetivo del juego es hacer que el conejito pueda cruzar las calles
 sin que lo atropelle ningu´n veh´iculo (ver Figura 1). Si un veh´iculo 
atropella al conejito, perdemos el juego.
Cabe aclarar, que en nuestro juego los veh´iculos y las calles se desplazan 
constantemente hacia abajo de la pantalla, creando la ilusi´on de “avance” del 
juego. Es decir, el conejo debe saltar hacia adelante para que no desaparezca 
por el borde inferior de la pantalla (cuando esto u´ltimo sucede se pierde el 
juego).



== Descripción



En esta sección pueden incluirse las dificultades que tuvieron, las
soluciones encontradas, las decisiones que se fueron tomando a lo largo
del trabajo práctico, y las cuestiones de diseño que consideren
importantes.

También, se puede incluir una descripción general del programa—cómo
funciona.

== Implementación

En esta sección se incluye el código fuente correctamente formateado—y
comentado, si corresponde.

Además, por cada fragmento de código
relevante—i.e. función, método, procedimiento—se debe dar una
breve descripción, decir qué hace, y especificar los parámetros que
toma la función/método/procedimiento, junto con los valores que devuelve
ó modifica.

_No debería incluirse el código de librerías/frameworks que se
utilicen—a no ser que sea absolutamente necesario._

== Conclusiones

Aquí van algunas reflexiones acerca del proceso de desarrollo del
trabajo realizado, y de los resultados obtenidos.

También se puede incluir una conclusión final de producto terminado.

Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.